set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
set_property PACKAGE_PIN AU11 [get_ports sys_clk_p]
set_property PACKAGE_PIN AV11 [get_ports sys_clk_n]

create_clock -period 5.000 -name sys_clk_p [get_ports sys_clk_p]
create_clock -period 10.000 -name gt_refclk1_0_clk_p [get_ports gt_refclk1_0_clk_p]

set_property PACKAGE_PIN P4  [get_ports {PCIE1_GT_0_grx_p[7]}]
set_property PACKAGE_PIN P3  [get_ports {PCIE1_GT_0_grx_n[7]}]
set_property PACKAGE_PIN N2  [get_ports {PCIE1_GT_0_grx_p[6]}]
set_property PACKAGE_PIN N1  [get_ports {PCIE1_GT_0_grx_n[6]}]
set_property PACKAGE_PIN L2  [get_ports {PCIE1_GT_0_grx_p[5]}]
set_property PACKAGE_PIN L1  [get_ports {PCIE1_GT_0_grx_n[5]}]
set_property PACKAGE_PIN K4  [get_ports {PCIE1_GT_0_grx_p[4]}]
set_property PACKAGE_PIN K3  [get_ports {PCIE1_GT_0_grx_n[4]}]
set_property PACKAGE_PIN J2  [get_ports {PCIE1_GT_0_grx_p[3]}]
set_property PACKAGE_PIN J1  [get_ports {PCIE1_GT_0_grx_n[3]}]
set_property PACKAGE_PIN H4  [get_ports {PCIE1_GT_0_grx_p[2]}]
set_property PACKAGE_PIN H3  [get_ports {PCIE1_GT_0_grx_n[2]}]
set_property PACKAGE_PIN G2  [get_ports {PCIE1_GT_0_grx_p[1]}]
set_property PACKAGE_PIN G1  [get_ports {PCIE1_GT_0_grx_n[1]}]
set_property PACKAGE_PIN F4  [get_ports {PCIE1_GT_0_grx_p[0]}]
set_property PACKAGE_PIN F3  [get_ports {PCIE1_GT_0_grx_n[0]}]

set_property PACKAGE_PIN R7  [get_ports {PCIE1_GT_0_gtx_p[7]}]
set_property PACKAGE_PIN R6  [get_ports {PCIE1_GT_0_gtx_n[7]}]
set_property PACKAGE_PIN N7  [get_ports {PCIE1_GT_0_gtx_p[6]}]
set_property PACKAGE_PIN N6  [get_ports {PCIE1_GT_0_gtx_n[6]}]
set_property PACKAGE_PIN M5  [get_ports {PCIE1_GT_0_gtx_p[5]}]
set_property PACKAGE_PIN M4  [get_ports {PCIE1_GT_0_gtx_n[5]}]
set_property PACKAGE_PIN L7  [get_ports {PCIE1_GT_0_gtx_p[4]}]
set_property PACKAGE_PIN L6  [get_ports {PCIE1_GT_0_gtx_n[4]}]
set_property PACKAGE_PIN J7  [get_ports {PCIE1_GT_0_gtx_p[3]}]
set_property PACKAGE_PIN J6  [get_ports {PCIE1_GT_0_gtx_n[3]}]
set_property PACKAGE_PIN G7  [get_ports {PCIE1_GT_0_gtx_p[2]}]
set_property PACKAGE_PIN G6  [get_ports {PCIE1_GT_0_gtx_n[2]}]
set_property PACKAGE_PIN F9  [get_ports {PCIE1_GT_0_gtx_p[1]}]
set_property PACKAGE_PIN F8  [get_ports {PCIE1_GT_0_gtx_n[1]}]
set_property PACKAGE_PIN E7  [get_ports {PCIE1_GT_0_gtx_p[0]}]
set_property PACKAGE_PIN E6  [get_ports {PCIE1_GT_0_gtx_n[0]}]

set_property IOSTANDARD LVSTL06_12 [get_ports {Alert_AB[0]}]

set_property IOSTANDARD LVSTL06_12 [get_ports {CA_A[3]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CA_A[2]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CA_A[1]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CA_A[0]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CA_B[3]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CA_B[2]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CA_B[1]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CA_B[0]}]

set_property IOSTANDARD LVSTL06_12 [get_ports {CS_A[1]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CS_A[0]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CS_B[1]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {CS_B[0]}]

set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {CK_A_p[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {CK_A_n[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {CK_B_p[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {CK_B_n[0]}]

set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[11]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[10]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[9]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[8]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[7]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[6]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[5]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[4]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[3]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[2]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[1]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_A[0]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[11]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[10]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[9]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[8]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[7]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[6]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[5]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[4]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[3]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[2]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[1]}]
set_property IOSTANDARD LVSTL06_12 [get_ports {DQ_B[0]}]

set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {RDQS_A_p[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {RDQS_A_n[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {RDQS_B_p[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {RDQS_B_n[0]}]

set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {WCK_A_p[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {WCK_A_n[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {WCK_B_p[0]}]
set_property IOSTANDARD DIFF_LVSTL06_12 [get_ports {WCK_B_n[0]}]

set_property SLEW FAST [get_ports {CA_A[3]}]
set_property SLEW FAST [get_ports {CA_A[2]}]
set_property SLEW FAST [get_ports {CA_A[1]}]
set_property SLEW FAST [get_ports {CA_A[0]}]
set_property SLEW FAST [get_ports {CA_B[3]}]
set_property SLEW FAST [get_ports {CA_B[2]}]
set_property SLEW FAST [get_ports {CA_B[1]}]
set_property SLEW FAST [get_ports {CA_B[0]}]
set_property SLEW FAST [get_ports {CK_A_p[0]}]
set_property SLEW FAST [get_ports {CK_A_n[0]}]
set_property SLEW FAST [get_ports {CK_B_p[0]}]
set_property SLEW FAST [get_ports {CK_B_n[0]}]
set_property SLEW FAST [get_ports {CS_A[1]}]
set_property SLEW FAST [get_ports {CS_A[0]}]
set_property SLEW FAST [get_ports {CS_B[1]}]
set_property SLEW FAST [get_ports {CS_B[0]}]
set_property SLEW FAST [get_ports {WCK_A_p[0]}]
set_property SLEW FAST [get_ports {WCK_A_n[0]}]
set_property SLEW FAST [get_ports {WCK_B_p[0]}]
set_property SLEW FAST [get_ports {WCK_B_n[0]}]

set_property PACKAGE_PIN BA18 [get_ports {Alert_AB[0]}]

set_property PACKAGE_PIN AR19 [get_ports {CA_A[3]}]
set_property PACKAGE_PIN AT21 [get_ports {CA_A[2]}]
set_property PACKAGE_PIN AT23 [get_ports {CA_A[1]}]
set_property PACKAGE_PIN AR20 [get_ports {CA_A[0]}]
set_property PACKAGE_PIN BB21 [get_ports {CA_B[3]}]
set_property PACKAGE_PIN BB20 [get_ports {CA_B[2]}]
set_property PACKAGE_PIN BB19 [get_ports {CA_B[1]}]
set_property PACKAGE_PIN BA21 [get_ports {CA_B[0]}]

set_property PACKAGE_PIN AN18 [get_ports {CK_A_p[0]}]
set_property PACKAGE_PIN AV18 [get_ports {CK_B_p[0]}]

set_property PACKAGE_PIN AT18 [get_ports {CS_A[1]}]
set_property PACKAGE_PIN AT22 [get_ports {CS_A[0]}]
set_property PACKAGE_PIN BA19 [get_ports {CS_B[1]}]
set_property PACKAGE_PIN BB18 [get_ports {CS_B[0]}]

set_property PACKAGE_PIN AV20 [get_ports {DQ_A[11]}]
set_property PACKAGE_PIN AP23 [get_ports {DQ_A[10]}]
set_property PACKAGE_PIN AV21 [get_ports {DQ_A[9]}]
set_property PACKAGE_PIN AU20 [get_ports {DQ_A[8]}]
set_property PACKAGE_PIN AM23 [get_ports {DQ_A[7]}]
set_property PACKAGE_PIN AU21 [get_ports {DQ_A[6]}]
set_property PACKAGE_PIN AL23 [get_ports {DQ_A[5]}]
set_property PACKAGE_PIN AL18 [get_ports {DQ_A[4]}]
set_property PACKAGE_PIN AN22 [get_ports {DQ_A[3]}]
set_property PACKAGE_PIN AM20 [get_ports {DQ_A[2]}]
set_property PACKAGE_PIN AM19 [get_ports {DQ_A[1]}]
set_property PACKAGE_PIN AL20 [get_ports {DQ_A[0]}]

set_property PACKAGE_PIN AN21 [get_ports {DQ_B[11]}]
set_property PACKAGE_PIN AN19 [get_ports {DQ_B[10]}]
set_property PACKAGE_PIN AW20 [get_ports {DQ_B[9]}]
set_property PACKAGE_PIN AP20 [get_ports {DQ_B[8]}]
set_property PACKAGE_PIN AP19 [get_ports {DQ_B[7]}]
set_property PACKAGE_PIN AW19 [get_ports {DQ_B[6]}]
set_property PACKAGE_PIN AY20 [get_ports {DQ_B[5]}]
set_property PACKAGE_PIN AY19 [get_ports {DQ_B[4]}]
set_property PACKAGE_PIN AW22 [get_ports {DQ_B[3]}]
set_property PACKAGE_PIN BA22 [get_ports {DQ_B[2]}]
set_property PACKAGE_PIN AY21 [get_ports {DQ_B[1]}]
set_property PACKAGE_PIN AY22 [get_ports {DQ_B[0]}]

set_property PACKAGE_PIN AL17 [get_ports {RDQS_A_p[0]}]
set_property PACKAGE_PIN AV22 [get_ports {RDQS_B_p[0]}]
set_property PACKAGE_PIN AL21 [get_ports {WCK_A_p[0]}]
set_property PACKAGE_PIN AV17 [get_ports {WCK_B_p[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports sys_rstn]
set_property PACKAGE_PIN J33 [get_ports sys_rstn]

set_property IOSTANDARD LVCMOS15 [get_ports {Reset_n[0]}]
set_property PACKAGE_PIN AW14 [get_ports {Reset_n[0]}]

set_property ODT RTT_40 [get_ports {Alert_AB[0]}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {CA_A[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {CA_A[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {CA_A[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {CA_A[0]}]
